src/Entity/TransactionAuto.php
<?php

namespace App\Entity;

use App\Repository\TransactionAutoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TransactionAutoRepository::class)
 */
class TransactionAuto
{
    // RT = Repeat Type
    const RT_YEARLY   = 'YEARLY';
    const RT_MONTHLY  = 'MONTHLY';
    const RT_WEEKLY   = 'WEEKLY';
    const RT_DAILY    = 'DAILY';

    const RT_LIST     = [
      self::RT_YEARLY,
      self::RT_MONTHLY,
      self::RT_WEEKLY,
      self::RT_DAILY,
    ];

    const ERR_UNKNOWN_RTYPE = -1;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\ManyToOne(targetEntity=BankAccount::class, inversedBy="transaction_autos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $bank_account;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $repeat_type;

    /**
     * @ORM\Column(type="date")
     */
    private $date_start;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_last;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $details;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getBankAccount(): ?BankAccount
    {
        return $this->bank_account;
    }

    public function setBankAccount(?BankAccount $bank_account): self
    {
        $this->bank_account = $bank_account;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getRepeatType(): ?string
    {
        return $this->repeat_type;
    }

    public function setRepeatType(string $repeat_type): self
    {
        $this->repeat_type = $repeat_type;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateLast(): ?\DateTimeInterface
    {
        return $this->date_last;
    }

    public function setDateLast(\DateTimeInterface $date_last): self
    {
        $this->date_last = $date_last;

        return $this;
    }

    public function getDetails(): ?string
    {
        return $this->details;
    }

    public function setDetails(?string $details): self
    {
        $this->details = $details;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }
}

src/Controller/AutomatonController.php
<?php

namespace App\Controller;

use App\Entity\TransactionAuto;
use App\Entity\User;
use App\Form\TransactionAutoType;
use App\Repository\CategoryRepository;
use App\Repository\TransactionAutoRepository;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Response;

/**
  * Require ROLE_USER for *every* controller method in this class.
  *
  * @IsGranted("ROLE_USER")
  */
class AutomatonController extends AbstractController
{
    private User $user;

    public function __construct(
        private TranslatorInterface $translator,
        private EntityManagerInterface $entityManager,
        private CategoryRepository $categoryRepository,
        private TransactionAutoRepository $transactionAutoRepository,
        Security $security,
    ) {
        $this->user = $security->getUser();
    }

    /**
     * @Route("/automaton/{id}", name="automaton", defaults={"id"=null})
     */
    public function index(?int $id, Request $request): Response
    {
        // Force user to create at least ONE bank account !
        if (count($this->user->getBankAccounts()) < 1)
            return $this->redirectToRoute('ignition-first-bank-account');

        $is_edit = (!empty($id) && ((int) $id) > 0);
        $return_data = [];

        // User has a bank account
        $default_bank_account = $this->user->getDefaultBankAccount();

        // Force user to add or import transaction(s) first
        if (count($default_bank_account->getTransactions()) < 1)
            return $this->redirectToRoute('ignition-first-transaction');

        // Initialize default message & change entity if needed
        if($is_edit) {
            // Get transaction auto to edit with id AND user (for security)
            $trans_auto_entity = $this->transactionAutoRepository->findOneByIdAndUser($id, $this->user);
            $message_status_ok = $this->translator->trans('form_trans_auto.status.edit_ok');
            $message_status_nok = $this->translator->trans('form_trans_auto.status.edit_nok');
        } else {
            // New Entity
            $trans_auto_entity = new TransactionAuto();
            $message_status_ok = $this->translator->trans('form_trans_auto.status.add_ok');
            $message_status_nok = $this->translator->trans('form_trans_auto.status.add_nok');
        }

        // 1) Build the form
        $trans_auto_form = $this->createForm(TransactionAutoType::class, $trans_auto_entity, ['type_form' => $is_edit ? 'edit' : 'add']);

        // 2) Handle the submit (will only happen on POST)
        $trans_auto_form->handleRequest($request);

        // 2.1) Form is submitted
        if ($trans_auto_form->isSubmitted()) {
            // Data to return/display
            $return_data = [
                'query_status' => 0,
                'slug_status' => 'error',
                'message_status' => $message_status_nok
            ];

            if ($trans_auto_form->isValid()) {
                // 3) Add some data to entity
                $trans_auto_entity->setBankAccount($default_bank_account);
                $trans_auto_entity->setIsActive(true);

                // 4) Save by persisting entity
                $this->entityManager->persist($trans_auto_entity);

                // 5) Try or clear
                try {
                    // Flush OK !
                    $this->entityManager->flush();

                    $return_data = [
                        'query_status' => 1,
                        'slug_status' => 'success',
                        'message_status' => $message_status_ok,
                        // Data
                        // 'entity' => self::format_json($trans_auto_entity),
                        // 'default_bank_account' => self::format_json_bank_account($default_bank_account)
                    ];
                } catch (\Exception $e) {
                    $this->entityManager->clear();
                    $return_data['exception'] = $e->getMessage();
                }
            }
        }

        // Retrieve transactions auto
        $return_data['trans_auto'] = $this->transactionAutoRepository->findAllByBankAccount($default_bank_account);

        // Retrieve total auto expenses & incomes
        $return_data['total_auto_expenses'] = $this->transactionAutoRepository->findTotal($default_bank_account, 'expenses');
        $return_data['total_auto_incomes'] = $this->transactionAutoRepository->findTotal($default_bank_account, 'incomes');

        if ($request->isXmlHttpRequest()) {
            return $this->json($return_data);
        } else {
            // Set message in flashbag on direct access
            if (isset($return_data['slug_status']) && isset($return_data['message_status'])) {
                /** @var Session $session */
                $session = $request->getSession();
                $session->getFlashBag()->add($return_data['slug_status'], $return_data['message_status']);
            }

            // Redirect to home after form submit to clear it
            if ($trans_auto_form->isSubmitted())
                return $this->redirectToRoute('automaton');

            return $this->render('automaton/index.html.twig', [
                'core_class'  => 'app-core--automaton app-core--merge-body-in-header',
                'meta'        => [ 'title' => $this->translator->trans('page.trans_auto.meta.title') ],
                'page_title'  => '<span class="icon icon-command"></span> ' . $this->translator->trans('page.trans_auto.title'),
                'is_trans_auto_edit'    => $is_edit,
                'form_trans_auto'       => $trans_auto_form->createView(),
                'default_category'      => $is_edit ? $trans_auto_entity->getCategory() : $this->categoryRepository->findDefault(),
                'trans_auto'            => $return_data['trans_auto'],
                'total_auto_expenses'   => $return_data['total_auto_expenses'],
                'total_auto_incomes'    => $return_data['total_auto_incomes'],
                'ta_repeat_types_list'  => TransactionAuto::RT_LIST,
            ]);
        }
    }

    /**
     * @Route("/trans-auto/delete/{id}", name="automaton_trans_auto_delete")
     */
    public function trans_auto_delete(int $id, Request $request): Response
    {
        $trans_auto = $this->transactionAutoRepository->findOneByIdAndUser($id, $this->user);
        $return_data = [
            'query_status' => 0,
            'slug_status' => 'error',
            'message_status' => $this->translator->trans('form_trans_auto.status.delete_nok')
        ];

        if(!is_null($trans_auto)) {
            $trans_auto_deleted = $trans_auto;
            $id_trans_auto_deleted = $trans_auto_deleted->getId();

            // Remove entity
            $this->entityManager->remove($trans_auto);

            // Try to save (flush) or clear entity remove
            try {
                $this->entityManager->flush();

                $return_data = [
                    'query_status' => 1,
                    'slug_status' => 'success',
                    'message_status' => $this->translator->trans('form_trans_auto.status.delete_ok'),
                    // Data
                    'entity' => [ 'id' => $id_trans_auto_deleted ],
                    // 'default_bank_account' => self::format_json_bank_account($this->user->getDefaultBankAccount())
                ];
            } catch (\Exception $e) {
                $this->entityManager->clear();
                $return_data['exception'] = $e->getMessage();
            }
        } else {
            $return_data['message_status'] = $this->translator->trans('form_trans_auto.status.delete_unknown_entity');
        }

        if ($request->isXmlHttpRequest()) {
            return $this->json($return_data);
        } else {
            /** @var Session $session */
            $session = $request->getSession();
            // Set message in flashbag on direct access
            $session->getFlashBag()->add($return_data['slug_status'], $return_data['message_status']);

            // Redirect to previous page (= referer)
            return $this->redirect($request->headers->get('referer'));
        }
    }
}

templates/automaton/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-6 col-xl-5 mb-3 mb-lg-0 order-lg-last align-self-start position-lg-sticky top-lg-3">
      <div class="card">
        <div class="card-header">
        {% if is_trans_auto_edit == true %}
          <h3 class="h4 mb-0">{{ 'page.trans_auto.form.title_edit'|trans }}</h3>
        {% else %}
          <h3 class="h4 mb-0">{{ 'page.trans_auto.form.title'|trans }}</h3>
        {% endif %}
        </div>
        <div class="card-body">
          {{ form_start(form_trans_auto) }}
            {% include 'components/forms/transaction-auto.html.twig' with { is_edit: is_trans_auto_edit } %}

            <div class="mt-2 text-center">
              <button class="btn btn-primary mx-1" type="submit" name="submit">
              {% if is_trans_auto_edit == true %}
                <span class="icon icon-edit"></span>
                Modifier
              {% else %}
                <span class="icon icon-plus-square"></span>
                Ajouter
              {% endif %}
              </button>
            </div>
          {{ form_end(form_trans_auto) }}
        </div>
      </div>
    </div>
    <div class="col-12 col-lg-6 col-xl-7">
      <div class="card">
        {#<div class="card-header">
          <h3 class="h4 mb-0">{{ 'page.trans_auto.list.title'|trans }}</h3>
        </div>#}
        {% if trans_auto is not empty %}
          <div class="list-with-actions list-transactions -no-scroll py-1">
          {% for ta in trans_auto %}
            <div class="-item -item-transac" data-kb-id-transaction="{{ ta.id }}">
              {# TRANS:CATEGORY/ICON & COLOR #}
              <div class="col col-auto col-icon">
                <span class="-transac-category avatar" title="{{ ta.category.label }}" data-toggle="tooltip" data-placement="top">
                  <span class="avatar-text rounded-circle" style="background-color: {{ ta.category.color }};">
                    <span class="icon icon-{{ ta.category.icon }}"></span>
                  </span>
                </span>
              </div>
              {# TRANS:TEXT #}
              <div class="col col-text">
                <span class="-transac-label">{{ ta.label }}</span>
              {% if ta.details is not empty %}
                <div class="-transac-details -more-info small text-muted">
                  {{ ta.details }}
                </div>
              {% endif %}
              </div>
              {# TRANS:REPEAT TYPE & LAST|NEXT EXEC. #}
              <div class="col col-repeat-type d-none d-sm-block d-lg-none d-xl-block text-right">
                <input class="form-control form-control-sm" type="text" name="trans-auto-repeat-type" disabled="disabled" value="{{ ('global.repeat_types.' ~ ta.repeatType)|trans }}"/>
                {% if ta.dateLast is not empty %}
                  <span class="icon icon-help-circle" title="{{ 'page.trans_auto.list.last_exec'|trans({ '%date%': ta.dateLast|format_datetime('long', 'none') })|raw }}"
                    data-toggle="tooltip" data-placement="left" data-html="true"></span>
                {% else %}
                  <span class="icon icon-help-circle" title="{{ 'page.trans_auto.list.next_exec'|trans({ '%date%': ta.dateStart|format_datetime('long', 'none') })|raw }}"
                    data-toggle="tooltip" data-placement="left" data-html="true"></span>
                {% endif %}
              </div>
              {# TRANS:AMOUNT/PRICE #}
              <div class="col col-price">
                {% include 'components/price.html.twig' with {
                  amount        : ta.amount,
                  currency      : ta.bankAccount.currency.label,
                  custom_class  : '-transac-amount' } %}
              </div>
              {# TRANS:ACTIONS #}
              <div class="col col-more">
                <a class="btn btn-sm btn-pill btn-outline-secondary mr-1" href="{{ path('automaton', { id: ta.id }) }}">
                  <span class="icon icon-edit"></span>
                </a>
                <button class="btn btn-sm btn-pill btn-outline-danger" type="button" data-confirm-href="{{ path('automaton_trans_auto_delete', { id: ta.id }) }}"
                  data-confirm-title="Confirmer la suppression" data-confirm-theme="danger" data-confirm-btn-text="Supprimer"
                    data-confirm-body="Êtes-vous sûr de vouloir supprimer la transaction récurrente : <br><b>&laquo;&nbsp;{{ ta.label }}&nbsp;&raquo;</b> ?"
                      data-toggle="modal" data-target="#modal-confirm">
                  <span class="icon icon-trash"></span>
                </button>
              </div>
            </div>
          {% endfor %}
          </div>
        {% else %}
          <div class="card-body">
            <div class="alert alert-secondary my-3">
              {{ 'page.trans_auto.list.empty'|trans }}
            </div>
          </div>
        {% endif %}
      </div>

      <div class="mt-4">
        {% include 'components/incomes-and-expenses.html.twig' with {
          expenses: total_auto_expenses,
          incomes: total_auto_incomes,
          bank_account: app.user.getDefaultBankAccount(),
          no_subtext: true
        } %}
      </div>
    </div>
  </div>
</div>
{% endblock %}