src/Entity/BankAccount.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BankAccountRepository")
 */
class BankAccount
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $label;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Transaction", mappedBy="bank_account", orphanRemoval=true)
     * @ORM\JoinColumn(nullable=true)
     * @ORM\OrderBy({"date" = "DESC", "id" = "DESC"})
     */
    private $transactions;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BankBrand", fetch="EAGER")
     * @ORM\JoinColumn(nullable=true)
     */
    private $bank_brand;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Currency", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $currency;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bankAccounts", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $is_default = false;

    /**
     * @ORM\OneToMany(targetEntity=TransactionAuto::class, mappedBy="bank_account", orphanRemoval=true)
     */
    private $transaction_autos;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $is_archived = false;

    public function __construct($user)
    {
        $this->transactions = new ArrayCollection();

        $this->setUser($user);
        $this->transaction_autos = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setBankAccount($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->contains($transaction)) {
            $this->transactions->removeElement($transaction);
            // set the owning side to null (unless already changed)
            if ($transaction->getBankAccount() === $this) {
                $transaction->setBankAccount(null);
            }
        }

        return $this;
    }

    public function getBankBrand(): ?BankBrand
    {
        return $this->bank_brand;
    }

    public function setBankBrand(?BankBrand $bank_brand): self
    {
        $this->bank_brand = $bank_brand;

        return $this;
    }

    public function getCurrency(): ?Currency
    {
        return $this->currency;
    }

    public function setCurrency(?Currency $currency): self
    {
        $this->currency = $currency;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getIsDefault(): bool
    {
        return $this->is_default;
    }


    public function isDefault(): bool
    {
        return $this->is_default;
    }

    public function setIsDefault(bool $is_default): self
    {
        $this->is_default = $is_default;

        return $this;
    }

    /**
     * @return Collection|TransactionAuto[]
     */
    public function getTransactionAutos(): Collection
    {
        return $this->transaction_autos;
    }

    public function addTransactionAuto(TransactionAuto $transactionAuto): self
    {
        if (!$this->transaction_autos->contains($transactionAuto)) {
            $this->transaction_autos[] = $transactionAuto;
            $transactionAuto->setBankAccount($this);
        }

        return $this;
    }

    public function removeTransactionAuto(TransactionAuto $transactionAuto): self
    {
        if ($this->transaction_autos->removeElement($transactionAuto)) {
            // set the owning side to null (unless already changed)
            if ($transactionAuto->getBankAccount() === $this) {
                $transactionAuto->setBankAccount(null);
            }
        }

        return $this;
    }

    public function getIsArchived(): bool
    {
        return $this->is_archived;
    }

    public function isArchived(): bool
    {
        return $this->is_archived;
    }

    public function setIsArchived(bool $is_archived): self
    {
        $this->is_archived = $is_archived;

        return $this;
    }

    public function toggleIsArchived(): self
    {
        $this->is_archived = !$this->is_archived;

        return $this;
    }
}

src/Entity/User.php
<?php
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=190, unique=true)
     * @Assert\Email()
     */
    private $email;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=4096)
     */
    private $plainPassword;

    /**
     * The below length depends on the "algorithm" you use for hashing
     * the password, but this works well with bcrypt.
     *
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $role;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\Type("\DateTimeInterface")
     */
    private $registerDate;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Category", mappedBy="user", cascade={"remove"})
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\BankAccount", mappedBy="user", cascade={"remove"}, orphanRemoval=true)
     */
    private $bankAccounts;

    public function __construct()
    {
        $this->isActive = true;
        // TODO add the user's Timezone
        $this->registerDate = new \DateTime();
        $this->categories = new ArrayCollection();
        $this->bankAccounts = new ArrayCollection();
        // may not be needed, see section on salt below
        // $this->salt = md5(uniqid('', true));
    }

    public function getId()
    {
        return $this->id;
    }

    // Register date (= now())
    public function getRegisterDate(): ?\DateTimeInterface
    {
        return $this->registerDate;
    }

    // Email
    public function getEmail()
    {
        return $this->email;
    }

    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    // Username
    public function getUsername()
    {
        return $this->username;
    }

    public function setUsername($username)
    {
        $this->username = $username;
    }

    public function getUserIdentifier()
    {
        return $this->username;
    }

    // Pain password
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;

        return $this;
    }

    // Password
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    // Salt
    public function getSalt()
    {
        return null;
    }

    // Roles
    public function getRoles()
    {
        return array(empty($this->role) ? 'ROLE_USER' : $this->role);
    }

    public function setRole($role)
    {
        $this->role = $role;

        return $this;
    }

    public function getRole(): string
    {
        return $this->role;
    }

    // Active/lock/expired methods
    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->isActive;
    }

    public function getIsActive()
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive)
    {
        $this->isActive = $isActive;
    }

    // Credentials & Serialize
    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setUser($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
            // set the owning side to null (unless already changed)
            if ($category->getUser() === $this) {
                $category->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|BankAccount[]
     */
    public function getBankAccounts(): Collection
    {
        return $this->bankAccounts;
    }

    /**
     * @return Collection|BankAccount[]
     */
    public function getBankAccountsActive(): Collection
    {
        return $this->bankAccounts->filter(static fn (BankAccount $bankAccount) => false === $bankAccount->isArchived());
    }

    public function addBankAccount(BankAccount $bankAccount): self
    {
        if (!$this->bankAccounts->contains($bankAccount)) {
            $this->bankAccounts[] = $bankAccount;
            $bankAccount->setUser($this);
        }

        return $this;
    }

    public function removeBankAccount(BankAccount $bankAccount): self
    {
        if ($this->bankAccounts->contains($bankAccount)) {
            $this->bankAccounts->removeElement($bankAccount);
            // set the owning side to null (unless already changed)
            if ($bankAccount->getUser() === $this) {
                $bankAccount->setUser(null);
            }
        }

        return $this;
    }

    public function hasManyBankAccounts(): bool
    {
        return count($this->getBankAccounts()) > 1;
    }

    public function getDefaultBankAccount(): ?BankAccount
    {
        $criteria = Criteria::create();
        $criteria->where(Criteria::expr()->eq('is_default', true));

        $matches = $this->bankAccounts->matching($criteria);

        return (count($matches) > 0) ? $matches->first() : null;
    }
}

templates/components/menu/bank-account-select.html.twig
{% set bank_accounts = app.user.bankAccountsActive %}

{% if bank_accounts is not empty %}
  {% set default_bank_account = app.user.defaultBankAccount %}
  <div class="navbar-bank-account dropdown border-right order-{{ size_display_menu }}-10 mr-3 pr-3">
    <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <div class="d-inline-block align-middle">
        <div class="bank-account-label">
          {{ default_bank_account.label }}
        </div>
        <div class="bank-account-balance">
          {{ 'menu.balance.label'|trans }} : {% include 'components/price.html.twig' with {
              amount : default_bank_account|balance,
              currency : default_bank_account.currency.label } %}
        </div>
      </div>
    </div>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
      <div class="dropdown-header">{{ 'menu.bank_accounts.title'|trans }}</div>
      {% for ba in bank_accounts %}
        {% if ba.id == default_bank_account.id %}
          <div class="dropdown-item active">
            {{ ba.label }}<br>
            <span class="text-muted small">
              <span class="currency">{{ ba.currency.label }}</span> -
              {{ ba.bankBrand.label }}
            </span>
          </div>
        {% else %}
          <a class="dropdown-item" href="{{ path('bank_accounts_switch_default', { id: ba.id }) }}">
            {{ ba.label }}<br>
            <span class="text-muted small">
              <span class="currency">{{ ba.currency.label }}</span> -
              {{ ba.bankBrand.label }}
            </span>
          </a>
        {% endif %}
      {% endfor %}

      <div class="dropdown-divider"></div>

      <div class="text-center px-3" style="min-width: 14rem;">
        <a href="{{ path('bank_accounts') }}" class="btn btn-primary">
          {{ 'menu.bank_accounts.btn_manage.label'|trans }}
        </a>
      </div>
    </div>
  </div>
{% endif %}

templates/components/menu/user.html.twig
<div class="navbar-user dropdown order-{{ size_display_menu }}-12">
  {% if app.user is not null and app.user.username is defined %}
    <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="say-hello mr-1 d-none d-lg-inline">
        {{ 'menu.say_hello'|trans({'%name%': app.user.username})|raw }}
      </span>

      {% include 'components/user/avatar.html.twig' %}
    </div>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
      {% if app.request.attributes.get('_route') == 'home' %}
      <a class="dropdown-item" href="{{ path('dashboard') }}">
        <span class="icon icon-settings"></span>
        {{ 'menu.user.dashboard.label'|trans }}
      </a>
      {% endif %}
      <a class="dropdown-item{% if app.request.attributes.get('_route') == 'user_profile' %} active{% endif %}" href="{{ path('user_profile') }}">
        <span class="icon icon-user"></span>
        {{ 'menu.user.profile.label'|trans }}
      </a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{{ path('logout') }}">
        <span class="icon icon-power"></span>
        {{ 'menu.user.logout.label'|trans }}
      </a>
    </div>
  {% else %}
    <div class="btn-group btn-group-sm">
      <a href="{{ path('user_registration') }}" class="btn btn-outline-primary text-white">
        Inscription
      </a>
      <a href="{{ path('login') }}" class="btn btn-primary">
        Connexion
      </a>
    </div>
  {% endif %}
</div>